#!/bin/sh
# pk-zypp-nemo-remove-old-cache: Remove old files after move to /home/ (JB#29268)

# the outdated cache location that is to be removed
OLD_CACHE=/var/cache/pk-zypp-dist-upgrade

# it is always safe to remove the old location, even if the new location does
# not exist, at the time of the oneshot-execution
if [ -d "${OLD_CACHE}" ]; then
  rm -rf "${OLD_CACHE}" >/dev/null 2>&1
  exit $?
fi
